Add files via upload
I had problems pushing and pulling from GIT, had to manually upload these files here. 
>>> C:/Program Files/Git/bin/git.exe push origin HEAD:refs/heads/master
To https://github.com/Huapis/IODS-project.git
 ! [rejected]        HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/Huapis/IODS-project.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.